name: C Program CI/CD

on:
    push:
    
    workflow_dispatch:
    
jobs:
    build_and_run:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout repository
          uses: action/checkout@v4
          
        - name: Install GCC
          uses: sudo apt-get install -y gcc
          
        - name: Compile C program
          uses: gcc -o output leapyear.c
          
        - name: Run the program
          uses: ./output
